projects:
  gogoweb:
    schemaPath: amplify/backend/api/gogoweb/build/schema.graphql
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        region: ap-southeast-2
        apiId: null
        maxDepth: 4
extensions:
  amplify:
    version: 3
